config/routes.rb
Staj::Application.routes.draw do
  root to: "home#index"

  resources :probations

  devise_for :users

  get "commission/index"
  get "institution/index"
  get "student/index"

  match "/about" => "home#about"
  match "/contact" => "home#contact"

  match "/student/proselects" => "student#proselects"
  match "/student/settings" => "student#settings"
  match "/student/reports" => "student#reports"
  match "/student/probook" => "student#probook"
  match "/student/documents" => "student#documents"
  match "student" => "student#index"
  namespace :student do
    get   'settings'
    post  'settings_save'
    get   'password'
    post  'password_save'
  end

  match "/commission/index" => "commission#index"
  match "/commission/reports" => "commission#reports"
  match "/commission/settings" => "commission#settings"
  match "/commission/users" => "commission#users"

  match "/institution/index" => "institution#index"
  match "/institution/settings" => "institution#settings"
  match "/institution/reports" => "institution#reports"
  match "/institution/requests" => "institution#requests"
  match "/institution/proselects" => "probations#index"
  match "/institution/proselects/new" => "probations#new"
  match "/institution/proselects/:id/edit" => "probations#edit"
  match "/institution/proselects/:id" => "probations#show", via: :get
  match "/institution/proselects/:id" => "probations#update", via: :put
  match "/institution/proselects/:id" => "probations#destroy", via: :delete

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.role? :ogrenci
      can :read, Probation
    end
    
    if user.role? :kurum
      can :read, Probation
      can :manage, Probation, user_id:user.id
    end

    if user.role? :komisyon
      can :manage, Probation
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/probation.rb
class Probation < ActiveRecord::Base
  attr_accessible :staj_yeri, :tarih, :tur
  belongs_to :user
end

app/models/student.rb
class Student < ActiveRecord::Base

  has_secure_password

  attr_accessible :tc, :first_name, :last_name, :email,
    :password, :password_confirmation, :phone_number,
    :image, :gender, :birthday, :status, :point, :address

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :first_name, :last_name, :email, :no, :password, :password_confirmation, :remember_me, :role
  # attr_accessible :title, :body
  ROLES = %w[ogrenci kurum komisyon]

  def role?(base_role)
    ROLES.index(base_role.to_s) <= ROLES.index(role)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #rescue_from CanCan::AccessDenied do |exception|
    #redirect_to root_path, :alert => exception.message
  #end
  # protect_from_forgery
  def after_sign_in_path_for(resources)
    email = User.find(current_user.id).email.gsub(/@\w+.[A-z]+.[A-z]{2,4}+.[A-z]{2,4}/,'')
    email = email.sub(/[.]/,'')
    case current_user.role
    when "ogrenci"
      "/student/index"
    when "kurum"
      "/institution/index"
    when "komisyon"
      "/commission/index"
    end
  end
end
  

app/controllers/commission_controller.rb
class CommissionController < ApplicationController
  before_filter :authenticate_user!
  def index
    #authorize! :index, @user, :message => 'Not authorized as an administrator.'
    #@user = User.all
  end
  def users

  end
  def reports

  end
  def settings

  end
  #def content
   # email = User.find(current_user_id).email.gsub(/@\w+.[A-z]+.[A-z]{2,4}+.[A,z]{2,4}/,'')
  #end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # @users = User.all
  end
  def contact

  end
  def about

  end
end

app/controllers/institution_controller.rb
class InstitutionController < ApplicationController
  before_filter :authenticate_user!
  def index

  end
  def reports

  end
  def requests

  end
  def settings

  end
end

app/controllers/probations_controller.rb
class ProbationsController < ApplicationController
  # GET /probations
  # GET /probations.json
  before_filter :authenticate_user!
  load_and_authorize_resource

  def index
    @probations = Probation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @probations }
    end
  end

  # GET /probations/1
  # GET /probations/1.json
  def show
    @probation = Probation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @probation }
    end
  end

  # GET /probations/new
  # GET /probations/new.json
  def new
    @probation = Probation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @probation }
    end
  end

  # GET /probations/1/edit
  def edit
    @probation = Probation.find(params[:id])
  end

  # POST /probations
  # POST /probations.json
  def create
    @probation = Probation.new(params[:probation])
    @probation.user = current_user
    respond_to do |format|
      if @probation.save
        format.html { redirect_to institution_index_path, notice: 'Probation was successfully created.' }
        format.json { render json: @probation, status: :created, location: @probation }
      else
        format.html { render action: "new" }
        format.json { render json: @probation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /probations/1
  # PUT /probations/1.json
  def update
    @probation = Probation.find(params[:id])
    @probation.user = current_user
    respond_to do |format|
      if @probation.update_attributes(params[:probation])
        format.html { redirect_to institution_proselects_path, notice: 'Probation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @probation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /probations/1
  # DELETE /probations/1.json
  def destroy
    @probation = Probation.find(params[:id])
    @probation.destroy

    respond_to do |format|
      format.html { redirect_to institution_proselects_path }
      format.json { head :no_content }
    end
  end
end

app/controllers/student_controller.rb
class StudentController < ApplicationController
  before_filter :authenticate_user!
  def index
    #authorize! :index, @user, :message => 'Not authorized as an administrator.'
    #@user = User.all
  end

  def settings_save
    student = Student.update(current_user.id, {
      :tc => params[:tc],
      :first_name => params[:first_name],
      :last_name => params[:last_name],
      :gender => params[:gender],
      :birthday => params[:birthday],
      :email => params[:email],
      :phone_number => params[:phone_number],
      :address => params[:address],
    })
    redirect_to '/student/settings' 
  end

  def password_save

  end

  def proselects


  end

  def settings

  end

  def documents

  end

  def probook

  end

  def reports

  end
  #def content
    # email = User.find(current_user_id).email.gsub(/@\w+.[A-z]+.[A-z]{2,4}+.[A,z]{2,4}/,'')
  #end  
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/commission_helper.rb
module CommissionHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/institution_helper.rb
module InstitutionHelper
end

app/helpers/probations_helper.rb
module ProbationsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/commission/_commissionmenu.html.slim
.ortala
  ul.nav
    li.divider
    li
      a href="index"
        | AnaSayfa
    li
      a href="users"
        | Kullanıcı İşlemleri
    li
      a href="reports"
        | Stajyer Değerlendirme
    li
      a href="settings"
        | Sistem Ayarları
    li
      = link_to "Çıkış Yap", destroy_user_session_path, :method => :delete
    li
      p align="center"
      = current_user.email
  embed[src="http://img515.imageshack.us/img515/1949/saatfh0.swf" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" name="obj1" width="160" height="160"]
  noscript
    a[href="http://www.venus.gen.tr/ekle/"]
      | Sitene Ekle    

app/views/commission/index.html.slim
.arka
  h3 Komisyon Menü

app/views/commission/reports.html.slim
.arka
  h3 Stajyer değerlendirme bu alanda yapılmaktadır.

app/views/commission/settings.html.slim
.arka
  h3 Sistem Ayarları

app/views/home/about.html.slim
.hero-unit
  center
    p
      | Staj Yönetim Sistemi; staj yapmak isteyen öğrencilerin online olarak başvuru ve kayıt yapabilmesini, sisteme daha önceden kayıt yaptırmış ve onay almış kurumların ilan verebilmesini ve akademisyenlerin ilgili stajı onaylamasını sağlayarak iş yükünü azaltmayı hedefleyen bir sistemdir.

app/views/home/contact.html.slim
.hero-unit
  center
    p
      | İletişim Bilgileri
      br/
      | Ondokuz Mayıs Üniversitesi Mühendislik Fakültesi
      br/
      | Bilgisayar Mühendisliği Bölümü
      br/
      | Kurupelit Kampüsü 55139 Kurupelit / Samsun
      br/
      br/
      | Telefon: (362) 312 19 19 (Santral)
      br/
      | Bölüm Başkanı Dahili Telefon: --
      br/
      | Sekreterlik Dahili Telefon: --
      br/
      | e-posta: project.staj@bil.omu.edu.tr
      br/
      br/
    dd
      iframe frameborder="0" height="260" marginheight="0" marginwidth="0" scrolling="no" src="http://maps.google.com/maps/ms?ie=UTF8&msa=0&msid=205688719925423347995.0004667d8f2be68866815&t=h&source=embed&ll=41.367211,36.19081&spn=0.008374,0.018454&z=15&output=embed" width="430"
      br/
      small
        | Haritada görmek için:
        a href="http://maps.google.com/maps/ms?ie=UTF8&msa=0&msid=205688719925423347995.0004667d8f2be68866815&t=h&source=embed&ll=41.367211,36.19081&spn=0.008374,0.018454&z=15" style="color:#0000FF;text-align:left"Ondokuz Mayıs Üniversitesi

app/views/home/index.html.slim
.arkaplan  
  body
    #myCarousel.carousel.slide
      .carousel-inner
        .item.active
          img[src="http://i.imgur.com/FK2bB.jpg" alt=""]
          .container
            .carousel-caption
              h1
                | Bilgisayar Mühendisliği Bölümü
              p.lead
                | Samsun Ondokuz Mayıs Üniversitesi
              a.btn.btn-large.btn-primary[href="http://bil.omu.edu.tr/a/" target="_blank"]
                | Bil.Mühendisliği
        .item
          img[src="http://i.imgur.com/Avm7g.jpg" alt=""]
          .container
            .carousel-caption
              h1
                | Kaynak Kodlarımız
              p.lead
                | Çok Çalıştık Başardık :)
              a.btn.btn-large.btn-danger[href="https://github.com/kcd/staj" target="_blank"]
                | Github deposu
        .item
          img[src="http://twitter.github.com/bootstrap/assets/img/examples/slide-01.jpg" alt=""]
          .container
            .carousel-caption
              h1
                | İş Planımız
              p.lead
                | İşlerimizi burada düzenledik.
              a.btn.btn-large.btn-warning[href="https://trello.com/board/project-staj" target="_blank"]
                | Trello
      a.left.carousel-control[href="#myCarousel" data-slide="prev"]
        | ‹
      a.right.carousel-control[href="#myCarousel" data-slide="next"]
        | › 

app/views/institution/_institutionmenu.html.slim
.ortala
  ul.nav
    li.divider
    li
      a href="index"
        | AnaSayfa
    li
      a href="proselects"
        | Staj İlanı
    li 
      a href="reports"
        | Stajyer Belgeleri 
    li
      a href="requests"
        | Staj Talep İşlemleri
    li
      a href="settings"
        | Kullanıcı Ayarları
    li 
      = link_to "Çıkış Yap", destroy_user_session_path, :method => :delete
    li
      p align="center"
      = current_user.email
  embed[src="http://img515.imageshack.us/img515/1949/saatfh0.swf" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" name="obj1" width="160" height="160"]
  noscript
    a[href="http://www.venus.gen.tr/ekle/"]
      | Sitene Ekle    

app/views/institution/content.html.slim
#Content Institution

app/views/institution/index.html.slim
.arka
  h3 Kurum Menü

app/views/institution/reports.html.slim
.arka
  h3 Stajyer değerlendirme belgelerinin bulunduğu alandır.

app/views/institution/requests.html.slim
.arka
  h3 Stajyer talep isteklerinin listelendiği alandır.

app/views/institution/settings.html.slim
.arka
  h3 Kullanıcı Ayarları

app/views/layouts/application.html.slim
doctype
html
  head
    title Staj Yönetim Sistemi
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  body
    .container.navbar-wrapper
      .navbar.navbar-inverse
        .navbar-inner
          ul.nav
            li
              a href="http://www.omu.edu.tr"19 Mayıs Üniversitesi
            li
              a href="/"Anasayfa
            li
              a href="/about.html"Hakkımızda
            li
              a href="/contact.html"İletişim
            li
              a href="/users/sign_in"Giriş
        = yield
        - flash.each do |key, value|
          = content_tag :div, value
      - if current_user
        - if current_user.role == "ogrenci"
          = render 'studentmenu'
        - if current_user.role == "kurum"
          = render "institutionmenu"
        - if current_user.role == "komisyon"
          = render 'commissionmenu'

app/views/probations/_form.html.slim
.text_area
  = form_for @probation, :html => { :class => "form-horizontal" } do |f|
    .control-group
      = f.label :staj_yeri, :class => 'control-label'
      .controls
        = f.text_field :staj_yeri, :class => 'text_field'
    .control-group
      = f.label :tur, :class => 'control-label'
      .controls
        = f.text_area :tur, :class => 'text_area'
    .control-group
      = f.label :tarih, :class => 'control-label'
      .controls
        = f.text_area :tarih, :class => 'text_area'
    .buton_orta
      = f.submit nil, :class => 'btn btn-primary'
      '
      = link_to t('.cancel', :default => t("helpers.links.cancel")),
        institution_proselects_path, :class => 'btn'
 

app/views/probations/_institutionmenu.html.slim
.ortala
  ul.nav
    li.divider
    li
      a href="/institution/index"
        | AnaSayfa
    li
      a href="/institution/proselects"
        | Staj İlanı
    li
      a href="/institution/reports"
        | Stajyer Belgeleri
    li
      a href="/institution/settings"
        | Kullanıcı Ayarları
    li
      = link_to "Çıkış Yap", destroy_user_session_path, :method => :delete
    li
      p align="center"
      = current_user.email
  embed[src="http://img515.imageshack.us/img515/1949/saatfh0.swf" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" name="obj1" width="160" height="160"]
  noscript
    a[href="http://www.venus.gen.tr/ekle/"]
      | Sitene Ekle        

app/views/probations/edit.html.slim
.arka
	- model_class = Probation
	div class="page-header"
	  h3=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
	= render :partial => "form"

app/views/probations/index.html.slim
.arka
	- model_class = Probation
	div class="page-header"
	  h3=t '.title', :default => model_class.model_name.human.pluralize
	table class="table table-striped"
	  thead
	    tr
	      th= model_class.human_attribute_name(:id)
	      th= model_class.human_attribute_name(:staj_yeri)
	      th= model_class.human_attribute_name(:tur)
	      th= model_class.human_attribute_name(:tarih)

	      th= model_class.human_attribute_name(:created_at)
	      th=t '.actions', :default => t("helpers.actions")
	      th=t '.actions', :default => t("helpers.actions")
	  tbody
	    - @probations.each do |probation|
	      tr
	        td= link_to probation.id, "/institution/proselects/#{probation.id}"
	        td= probation.staj_yeri
	        td= probation.tur
	        td= probation.tarih
	        
	        td= probation.created_at
		  - if can? :edit, probation
		    td= link_to t('.edit', :default => t("helpers.links.edit")), "/institution/proselects/#{probation.id}/edit", :class => 'btn btn-mini'
		  - if can? :destroy, probation
		    td= link_to t('.destroy', :default => t("helpers.links.destroy")), "/institution/proselects/#{probation.id}", :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'
  
	= link_to t('.new', :default => t("helpers.links.new")), institution_proselects_new_path, :class => 'btn btn-primary'

app/views/probations/new.html.slim
|<spans yeni staj>
.arka
	- model_class = Probation
	div class="page-header"
	  h3=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
	= render :partial => "form"

app/views/probations/show.html.slim
- model_class = Probation
div class="page-header"
  h3=t '.title', :default => model_class.model_name.human

p
  strong= model_class.human_attribute_name(:staj_yeri) + ':'
  br
  = @probation.staj_yeri
p
  strong= model_class.human_attribute_name(:tur) + ':'
  br
  = @probation.tur
p
  strong= model_class.human_attribute_name(:tarih) + ':'
  br
  = @probation.tarih
p
  strong= model_class.human_attribute_name(:user_id) + ':'
  br
  = @probation.user_id

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")),
    instution_proselects_path, :class => 'btn'
  '
  = link_to t('.edit', :default => t("helpers.links.edit")),
    "/institution/proselects/#{@probation.id}/edit", :class => 'btn'

app/views/student/_studentmenu.html.slim
.ortala
  ul.nav
    li.divider
    li
      a href="index"
        | AnaSayfa
    li
      a href="reports"
        | Rapor
    li
      a href="proselects"
       | Staj Yeri Seçimi
    li
      a href="settings"
        | Kullanıcı Ayarları
    li
      a href="password"
        | Parola Değiştir
    li
      = link_to "Çıkış Yap", destroy_user_session_path, :method => :delete
    li
      p align="center"
      = current_user.email

app/views/student/content.html.slim
/!#Content
/

app/views/student/index.html.slim
.arka
  h3 Öğrenci Menü

app/views/student/password.slim
form.form-horizontal[action="/student/password_save" method="post" enctype="multipart/form-data"]
  fieldset
    legend
      | Parola Bilgileri
    .control-group
      label.control-label[for="input1"]
        | Kullandığınız Parola (*)
      .controls
        input#input1.input-xlarge.required[type="password" name="old_password"]
    .control-group
      label.control-label[for="input2"]
        | Yeni Parola (*)
      .controls
        input#input2.input-xlarge.required[type="password" name="new_password"]
    .control-group
      label.control-label[for="input3"]
        | Yeni Parola Tekrar (*)
      .controls
        input#input3.input-xlarge.required[type="password" name="new_password2"]
  .form-actions
    button.btn.btn-primary[type="submit"]
      | Parolamı Değiştir
    a.btn[href="/student/index"]
      | İptal

app/views/student/proselects.html.slim
.arka
  h3 Staj Yeri Seçimi

app/views/student/reports.html.slim
.arka
  h3 Rapor Ekle

app/views/student/settings.html.slim
form.form-horizontal[action="/student/settings_save" method="post" enctype="multipart/form-data"]
  fieldset
    legend
      | Kullanıcı Bilgileri Güncelleme Ekranı
    .control-group
      label.control-label[for="input-tc"]
        | Tc Kimlik Numarası (*)
      .controls
        input#input-tc.input-xlarge.required.digits[type="text" name="tc"]
    .control-group
      label.control-label[for="input02"]
        | Ad (*)
      .controls
        input#input02.input-xlarge.required[type="text" name="first_name"]
    .control-group
      label.control-label[for="input03"]
        | Soyad (*)
      .controls
        input#input03.input-xlarge.required[type="text" name="last_name"]
    .control-group
      label.control-label
        | Cinsiyet (*)
      .controls
        label.radio
          input#optionsRadios1[type="radio" name="gender" value="Erkek"] Erkek
        label.radio
          input#optionsRadios2[type="radio" name="gender" value="Bayan"] Bayan
    .control-group
      label.control-label[for="select11"]
        | Doğum Günü (*)
      .controls
        input#input3.input-xlarge.required[type="text" name="birthday" data-datepicker="datepicker"]
    .control-group
      label.control-label[for="fileInput"]
        | Fotoğraf
      .controls
        input#fileInput.input-file[type="file" name="image"]
  fieldset
    legend
      | İletişim Bilgileri
    .control-group
      label.control-label[for="input14"]
        | E-mail (*)
      .controls
        input#input14.input-xlarge.required.email[type="text" name="email"]
    .control-group
      label.control-label[for="input11"]
        | Telefon Numarası
      .controls
        input#input11.input-xlarge[type="text" name="phone_number"]
        p.help-block
          | Örneğin: 0506-693-4002
    .control-group
      label.control-label[for="input16"]
        | Adres
      .controls
        textarea#input16.input-xlarge[type="text" rows="3" name="address"]
  .form-actions
    button.btn.btn-primary[type="submit"]
      | Bilgilerimi Güncelle
    a.btn[href="/student/index"]
      | İptal

app/views/student/show.html.slim
/!.arkaplan
  h3 User
  p
    | User: #{@user.name}
  p
    | Email: #{@user.email if @user.email}
/